name: Payper
favicon: null
layout_spectrum: 0.27084744768217206
typography_spectrum: 0.5081727630458772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.26155993063002825
  lightness: 0.9025987801142037
  saturation: 0.7316191459540278
  rhythmicContrast: 0.23356875218451023
purpose: []
