name: Payper
favicon: null
layout_spectrum: 0.24321
typography_spectrum: 0.5081727630458772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00683f'
    - '#000000'
    - '#478e71'
    - '#87b7a3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.7316191459540278
  rhythmicContrast: 0.23356875218451023
purpose: []
